mkdir -p $INSTALL_TO/doc
sed -i -e 's/-O3 /-Og /g' SuiteSparse_config/SuiteSparse_config.mk
make -j8 install CUDA=no CFLAGS='-g -Og' CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX=$INSTALL_TO -DCMAKE_C_FLAGS='-g -Og' -DCMAKE_CXX_FLAGS='-g -Og' -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON" prefix=$INSTALL_TO INSTALL=$INSTALL_TO INSTALL_LIB=$INSTALL_TO/lib INSTALL_INCLUDE=$INSTALL_TO/include INSTALL_DOC=$INSTALL_TO/doc OPTIMIZATION='-Og'
